local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 3.0
  publish_frequency: 3.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true

  width: 10
  height: 10
  resolution: 0.05  

